
services:
  nextjs-app:
    image: nextjs-app
    container_name: nextjs-app
    build:
      context: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ./app:/app
      - node_modules:/app/node_modules
      - build:/app/.next
    env_file:
      - .env

volumes:
  node_modules:
  build: